- README.adoc
- pom.xml
- src/main/resources/application.properties
This is an alternative version on #14 where the config source (factory) is coming from its own project.
This will only work once https://github.com/RedHatInsights/clowder-quarkus-config-source/pull/1 is merged and released to central (or from local build).
cc @bennetelli @radcortez
> Pull in ClowderConfigSource

- .rhcicd/clowdapp.yaml
- The `/tmp` volume is now named `rds-client-ca` because it may be used by `clowder-quarkus-config-source` to write the RDS certificate. `notifications-gw` does not access the database yet, but this should change soon.
- Several container vars (`APP_NAME`, `ENV_NAME`, `PATH_PREFIX`...) have been removed because they seemed unused. We may need to reintroduce them in case something got broken by that change.
- `CLOWDER_FILE` container var replaced with `ACG_CONFIG`. It will actually work that way once https://github.com/RedHatInsights/clowder-quarkus-config-source/pull/41 is merged and we depend on it here. In the meantime, we will use the default path from `clowder-quarkus-config-source` which has the same value than `ACG_CONFIG` on ephemeral.
- Kafka topic configuration changed to match …
> NOTIF-336 Prepare clowdapp.yaml for cutover to Clowder deployed stage

- pom.xml
- src/main/java/com/redhat/cloud/notifications/GwResource.java
- src/main/java/com/redhat/cloud/notifications/RestAction.java
- src/main/java/com/redhat/cloud/notifications/RestRecipient.java
- src/test/java/com/redhat/cloud/notifications/GwResourceTest.java
This goes with https://github.com/RedHatInsights/notifications-backend/pull/595
Backwards compatibility is keep in the API (i.e. does not break if you don't send `recipients` settings)
> NOTIF-310 Allows recipients settings

- .rhcicd/clowdapp.yaml
This is the preferred deployment naming which is already used in most migrated Clowdapps.
> NOTIF-336 Fix clowdapp.yaml deployment name

- .rhcicd/clowdapp.yaml
The deployment failed on stage because of the missing dependency.
> Add notifications-backend in the ClowdApp dependencies

- src/main/java/com/redhat/cloud/notifications/clowder/KafkaSaslInitializer.java
Copied from [policies-engine](https://github.com/RedHatInsights/policies-engine/blob/master/external/src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java) which was successfully tested on `fedramp-stage` with SASL enabled.
> Init Kafka SASL config using Clowder

- src/main/java/com/redhat/cloud/notifications/GwResource.java
- src/main/java/com/redhat/cloud/notifications/NotificationsGwApp.java
- src/main/java/com/redhat/cloud/notifications/auth/RHIdAuthMechanism.java
- src/main/java/com/redhat/cloud/notifications/clowder/KafkaSaslInitializer.java
Quarkus recently introduced a new `Log` API which delegates all its invocations to `org.jboss.logging.Logger`. Building the logger is no longer needed.
> Use the new Quarkus Log API

- src/main/docker/Dockerfile-build.jvm
All pods are down on stage and the Fabric8 script is missing a permission to run:
```
exec /deployments/run-java.sh: permission denied
```
I don't know what caused that but we stopped using `run-java-sh` a long time ago in `notifications-backend` and we certainly don't need it in this project. This PR changes the Docker image generation to something almost identical to `notifications-backend`.
> Stop starting the app with io.fabric8:run-java-sh

- .rhcicd/do-nothing.yaml
Fixes:
```
error creating resource *v1.CronJob notifications-gw-do-nothing-job-9402433-do-nothing-gw: CronJob.batch "notifications-gw-do-nothing-job-9402433-do-nothing-gw" is invalid: metadata.name: Invalid value: "notifications-gw-do-nothing-job-9402433-do-nothing-gw": must be no more than 52 characters
```
> Rename do-nothing ClowdApp and job

- pom.xml
- src/main/java/com/redhat/cloud/notifications/GwResource.java
- src/main/java/com/redhat/cloud/notifications/RestValidationClient.java
- src/test/java/com/redhat/cloud/notifications/GwResourceTest.java
This is part 2.
See also [part 1](https://github.com/RedHatInsights/notifications-backend/pull/1519).
> NOTIF-496 Return 400 when validating invalid b/a/et triplet

- .rhcicd/clowdapp.yaml
This change will allow us to specify the Sentry DSN for the gateway on AppInterface.
[[RHCLOUD-22543]](https://issues.redhat.com/browse/RHCLOUD-22543)
> [RHCLOUD-22543] feature: parametrize the Sentry DSN

- pom.xml
- src/main/java/com/redhat/cloud/notifications/RestValidationClient.java
The Quarkus team strongly encourages all projects to switch from resteasy classic to resteasy reactive because former may no longer be supported soon. Since the gateway is gaining attention these days, we'll do that now.
> Replace resteasy classic with resteasy reactive

- pom.xml
- src/main/java/com/redhat/cloud/notifications/RestValidationClient.java
- src/main/resources/application.properties
:warning: Based on #361 which has to be merged first.
For each message received by notifications-gw, an HTTP call to notifications-backend is made to validate the bundle / application / event-type triplet. Since the B/A/ET rarely change in the DB, we can cache the call result in notifications-gw for better performances.
> RHCLOUD-29010 Cache the B/A/ET validation results

- .rhcicd/pr_check.sh
Until now, whenever we introduced a breaking change in the ClowdApp template and it broke the deployment in ephemeral, we had to deploy that template up to production before ephemeral could be fixed.
Starting now, deploying the new template in stage will be enough to fix ephemeral.
> Use ClowdApp template from stage in ephemeral

- src/main/resources/application.properties
Fixes
```
2023-10-25 11:47:32,501 WARN [com.red.clo.com.clo.con.ClowderConfigSource] (main) Endpoint 'notifications-backend-service' is using the old format. Please move to the new one: [Endpoint].[url|trust-store-path|trust-store-password|trust-store-type]
```
> Fix ClowderConfigSource warning at startup

- pom.xml
- src/main/resources/application.properties
The ClowdApp template already contained the settings for Sentry, but the Quarkus extension was missing :sweat_smile:
> RHCLOUD-29031 Introduce quarkus-logging-sentry extension

- pom.xml
Something's fishy with the pods memory. Let's see if 3.5.0 caused it.
> Revert "Bump Quarkus to 3.5.0 (#371)"

- pom.xml
Quarkus 3.5.x is causing `OutOfMemoryError: Java heap space` at container startup so we'll stick with 3.4.3 for a while... There's a discussion in progress with the Quarkus team about this.
> Downgrade Quarkus to 3.4.3 (again)

- pom.xml
The memory issue is still there... we can't bump to something more recent than 3.4.3.
> Downgrade Quarkus from 3.6.1 to 3.4.3

- src/main/docker/Dockerfile-build.jvm
> Stop printing JVM flags at startup

- .dockerignore
- .rhcicd/build_deploy.sh
* By generating a unique temporary directory for our builds, we ensure
that we will not share the workspace with the rest of the builds of the
platform.
* By explicitly ignoring the internal directories we ensure that we will
not copy them to our images by accident.
[[RHCLOUD-32001]](https://issues.redhat.com/browse/RHCLOUD-32001)
> RHCLOUD-32001 | Improve dockerfile builds

- .tekton/notifications-gw-pull-request.yaml
This is an experiment with a tech preview feature from Konflux.
**After** this PR has been merged, if the feature works as expected, the build of a pull request will only happen in Konflux if we add the `/konflux` comment in the PR.
https://pipelinesascode.com/docs/guide/authoringprs/#matching-a-pipelinerun-on-a-regexp-in-a-comment
> RHCLOUD-30193 Trigger Konflux build on comment

- pom.xml
Reverts RedHatInsights/notifications-gw#580
> Revert "Bump io.quarkiverse.logging.cloudwatch:quarkus-logging-cloudwatch from 6.9.0 to 6.11.0"

- .github/workflows/base-image-auto-update.yml
Use jq to query for image digest to remove the need to rely on skopeo inspect output having json keys in particular order. RHINENG-13679
> fix(CI): use jq in checkimage

- .rhcicd/clowdapp.yaml
- src/main/java/com/redhat/cloud/notifications/GwConfig.java
- src/main/java/com/redhat/cloud/notifications/GwResource.java
- src/main/java/com/redhat/cloud/notifications/NotificationsGwApp.java
- src/main/java/com/redhat/cloud/notifications/RestValidationClient.java
- src/main/java/com/redhat/cloud/notifications/model/SourceEnvironment.java
- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/notifications/GwResourceTest.java
The purpose of this PR is to allow usage of baet and certificates caches to get resilient regarding a notifications backend outage.
> [RHCLOUD-37354] Add notifications backend outage resilient caches
