- pom.xml
- src/main/java/com/redhat/cloud/notifications/ISO8601Timestamp.java
- src/main/java/com/redhat/cloud/notifications/RestAction.java
- src/main/java/com/redhat/cloud/notifications/SamplesResource.java
- src/main/java/com/redhat/cloud/notifications/TimestampValidator.java
- src/main/java/com/redhat/cloud/notifications/auth/IncomingRequestFilter.java
- src/main/java/com/redhat/cloud/notifications/auth/RbacFilter.java
- src/test/java/com/redhat/cloud/notifications/GwResourceTest.java
- src/test/java/com/redhat/cloud/notifications/RestActionValidationTest.java
- src/test/java/com/redhat/cloud/notifications/SamplesTest.java
- src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java
> Rework a bunch of things, improve validation,

- src/main/java/com/redhat/cloud/notifications/RestAction.java
> NOTIF-122 use snake_case

- deploy/clowdapp.yaml
to match the default of 8000. Also use a var for log level.
> Change port for health checks

- src/main/java/com/redhat/cloud/notifications/GwResource.java
- src/main/java/com/redhat/cloud/notifications/RestAction.java
- src/main/java/com/redhat/cloud/notifications/RestEvent.java
- src/main/java/com/redhat/cloud/notifications/RestMetadata.java
- src/main/java/com/redhat/cloud/notifications/SamplesResource.java
- src/test/java/com/redhat/cloud/notifications/GwResourceTest.java
- src/test/java/com/redhat/cloud/notifications/RestActionValidationTest.java
- src/test/java/com/redhat/cloud/notifications/SamplesTest.java
PS: I don't think /notifications/sample is used in GwResouce.java
> NOTIF-216 Aligning payload (REST and Kafka)

- pom.xml
- src/main/java/com/redhat/cloud/notifications/NotificationsGwApp.java
To be able to analyze logs in case of bugs and other issues, this commit adds git commit sha and message which gets printed during startup.
> NOTIF-175 Print git commit sha and message during startup

- pom.xml
With this PR, @dependabot will create one PR instead of two each time a new Quarkus release is available.
> Prevent dependabot Quarkus bump duplicates

- src/main/resources/application.properties
- src/test/java/com/redhat/cloud/notifications/NonApplicationRootPathTest.java
Same as https://github.com/RedHatInsights/notifications-backend/pull/501.
> Prevent non-application path regressions

- sonar-project.properties
Trying to enable sonarqube scanning for this project.
I found that the project has some java binaries so we need to set a path.
https://sonarqube.corp.redhat.com/dashboard?id=console.redhat.com%3Anotifications-gw
> Adding sonar properties

- src/main/java/com/redhat/cloud/notifications/clowder/KafkaSaslInitializer.java
Same as https://github.com/RedHatInsights/notifications-backend/pull/1344.
> RHCLOUD-20150 Connect to managed Kafka using Clowder

- .github/workflows/checkupdate.yml
> NOTIF-774 Automatically update ubi-minimal base image

- .rhcicd/do-nothing.yaml
Same as https://github.com/RedHatInsights/notifications-backend/pull/1471.
> Add envName to do-nothing.yaml

- .rhcicd/build_deploy.sh
Adding the date to the security compliance tag in the build script
> Adding date to security compliance tag

- src/main/java/com/redhat/cloud/notifications/GwResource.java
- src/main/java/com/redhat/cloud/notifications/RestAction.java
- src/main/java/com/redhat/cloud/notifications/RestRecipient.java
- src/main/java/com/redhat/cloud/notifications/SamplesResource.java
- src/test/java/com/redhat/cloud/notifications/GwResourceTest.java
Based on https://github.com/RedHatInsights/insights-schemas-java/pull/113.
> RHCLOUD-29101 Introduce recipients.emails field

- src/main/java/com/redhat/cloud/notifications/GwResource.java
- src/test/java/com/redhat/cloud/notifications/GwResourceTest.java
This was requested by OCM today. This PR is only the first step, we need to work on errors.
> Include details in the gateway response

- pom.xml
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.5
```
./mvnw io.quarkus.platform:quarkus-maven-plugin:3.5.0:update -N -Dstream=3.5
```
> Bump Quarkus to 3.5.0

- src/main/java/com/redhat/cloud/notifications/GwResource.java
These failure metrics will allow us to generate graphics and alerts based on the responses the gateway has been giving to calling services.
[[RHCLOUD-28943]](https://issues.redhat.com/browse/RHCLOUD-28943)
> RHCLOUD-28943 | feature: response failure metrics for the gateway

- src/main/java/com/redhat/cloud/notifications/GwResource.java
This PR contains a temporary workaround for the following exception which happens randomly:
```
2023-12-01 19:51:23,953 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-80) HTTP Request to /notifications failed, error id: 88a9935e-3136-488d-a3a6-f3137628fde7-1: java.util.ConcurrentModificationException
at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1522)
at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1517)
at org.jboss.resteasy.reactive.common.util.MultivaluedTreeMap.putAll(MultivaluedTreeMap.java:183)
at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.<init>(ClientReaderInterceptorContextImpl.java:67)
at …
```
> Add workaround for ConcurrentModificationException

- .tekton/notifications-gw-pull-request.yaml
> RHCLOUD-32273 Trigger Konflux builds with a GitOps command

- src/main/docker/Dockerfile-build.jvm
Same as https://github.com/RedHatInsights/notifications-backend/pull/2928.
> Fine-tune microdnf commands used while building images

- .tekton/notifications-gw-pull-request.yaml
- .tekton/notifications-gw-push.yaml
This reverts commit cfe9e9602a64e76c6155b607e53524a19f4ea29e.
> Revert "RHCLOUD-35654 Test a different remote pipeline spec path (#656)"

- .tekton/notifications-gw-pull-request.yaml
- .tekton/notifications-gw-push.yaml
Reverts RedHatInsights/notifications-gw#706
> Revert "Update dependency github.com/RedHatInsights/konflux-pipelines to v1.2.0"
